"use strict";

const ProjectsData = [{
	id: "project-1",
	title: "My personal website",
	type: "PERSONAL",
	company: null,
	companyLink: null,
	projectLink: "https://www.muralimanohar.in",
	githubLink: "https://github.com/muralimano28/personal-spa.git",
	technology: "HTML5 | CSS3 | Javascript (ES6) | React.js | Web design",
	description: "Developed a personal website to showcase my projects and experience.",
	tags: ["Personal"]
},
{
	id: "project-2",
	title: "DIY (Do it yourself) - Manage",
	type: "OFFICIAL",
	company: "Bookmyshow.com",
	companyLink: "https://www.bookmyshow.com",
	projectLink: "https://diy-in.bookmyshow.com/manage",
	githubLink: null,
	technology: "HTML5 | CSS3 | Javascript (ES5 & ES6) | React.js | Web design | Go | MongoDB | RethinkDB",
	description: "DIY - Do it yourself is a platform to create an event and sell tickets for that event",
	tags: ["Personal", "Inactive", "Incomplete", "Bookmyshow"]
},
{
	id: "project-3",
	title: "DIY (Do it yourself) - Microsite",
	type: "OFFICIAL",
	company: "Bookmyshow.com",
	companyLink: "https://www.bookmyshow.com",
	projectLink: "https://diy-in.bookmyshow.com",
	githubLink: null,
	technology: "HTML5 | CSS3 | Javascript (ES5 & ES6) | React.js | Web design | Go | MongoDB | RethinkDB",
	description: "DIY - Microsite is a themed page for showcasing event information",
	tags: []
},
{
	id: "project-4",
	title: "DIY (Do it yourself) - Discovery",
	type: "OFFICIAL",
	company: "Bookmyshow.com",
	companyLink: "https://www.bookmyshow.com",
	projectLink: "https://diy-in.bookmyshow.com",
	githubLink: null,
	technology: "HTML5 | CSS3 | Javascript (ES5 & ES6) | React.js | Web design | Go | MongoDB | RethinkDB",
	description: "DIY - Discovery is an events listing page.",
	tags: []
},
{
	id: "project-5",
	title: "Puppy pull",
	type: "PERSONAL",
	company: null,
	companyLink: null,
	projectLink: null,
	githubLink: "https://github.com/muralimano28/puppypull.git",
	technology: "HTML | Bootstrap | Javascript (ES5) | Angular.js",
	description: "Puppy pull is a simple web application that fetches photos of cute puppies from the flickr and displays it on a webpage. The visitors to the page can upvote and downvote an image. They can sort the images according to most voted one. Every image will display the number of votes it has received. It uses goflickr app that I created for back-end.",
	tags: ["Not active"]
},
{
	id: "project-6",
	title: "Goflickr",
	type: "PERSONAL",
	company: null,
	companyLink: null,
	projectLink: null,
	githubLink: "https://github.com/muralimano28/goflickr.git",
	technology: "Go | MongoDB | FlickrAPI",
	description: "Goflickr is an API which fetches images of puppies from flickr and stores them in MongoDB and serves it back to front-end application.",
	tags: ["Not active"]
},
{
	id: "project-7",
	title: "WaterD.com",
	type: "PERSONAL",
	company: null,
	companyLink: null,
	projectLink: null,
	githubLink: "https://github.com/muralimano28/waterD.com.git",
	technology: "HTML | Bootstrap | Javascript (ES5) | Angular.js | GoogleMaps API | MySQL | PHP",
	description: "WaterD.com is a website that helps user to located nearby shops that sell water bootles. But this project did not take off",
	tags: ["Incomplete"]
},
{
	id: "project-8",
	title: "Real-time locator with docking using google maps API for IOT",
	type: "OFFICIAL",
	company: "Aricent",
	companyLink: "http://www.aricent.com",
	projectLink: null,
	githubLink: null,
	technology: "HTML | Bootstrap | Javascript (ES5) | Angular.js | GoogleMaps API | .NET",
	description: "It is a single page application that get latitude and longitude info from server and places a marker in google maps in real time."
},
{
	id: "project-9",
	title: "TFTP - Trivial file transfer protocol",
	type: "OFFICIAL",
	company: "Aricent",
	companyLink: "http://www.aricent.com",
	projectLink: null,
	githubLink: null,
	technology: "C | SVN | RFC 1305",
	description: "Developed a C application to transfer small files from the server and to the server."
}
// ,
// {
// 	id: "project-10",
// 	title: "",
// 	type: "",
// 	company: "",
// 	projectLink: "",
// 	githubLink: "",
// 	duration: "",
// 	technology: "",
// 	description: "",
// 	teamSize: "",
// 	myContribution: ""
// },
// {
// 	id: "project-1",
// 	title: "",
// 	type: "",
// 	company: "",
// 	projectLink: "",
// 	githubLink: "",
// 	duration: "",
// 	technology: "",
// 	description: "",
// 	teamSize: "",
// 	myContribution: ""
// },
// {
// 	id: "project-1",
// 	title: "",
// 	type: "",
// 	company: "",
// 	projectLink: "",
// 	githubLink: "",
// 	duration: "",
// 	technology: "",
// 	description: "",
// 	teamSize: "",
// 	myContribution: ""
// },
// {
// 	id: "project-1",
// 	title: "",
// 	type: "",
// 	company: "",
// 	projectLink: "",
// 	githubLink: "",
// 	duration: "",
// 	technology: "",
// 	description: "",
// 	teamSize: "",
// 	myContribution: ""
// },
// {
// 	id: "project-1",
// 	title: "",
// 	type: "",
// 	company: "",
// 	projectLink: "",
// 	githubLink: "",
// 	duration: "",
// 	technology: "",
// 	description: "",
// 	teamSize: "",
// 	myContribution: ""
// },
// {
// 	id: "project-1",
// 	title: "",
// 	type: "",
// 	company: "",
// 	projectLink: "",
// 	githubLink: "",
// 	duration: "",
// 	technology: "",
// 	description: "",
// 	teamSize: "",
// 	myContribution: ""
// },
// {
// 	id: "project-1",
// 	title: "",
// 	type: "",
// 	company: "",
// 	projectLink: "",
// 	githubLink: "",
// 	duration: "",
// 	technology: "",
// 	description: "",
// 	teamSize: "",
// 	myContribution: ""
// },
// {
// 	id: "project-1",
// 	title: "",
// 	type: "",
// 	company: "",
// 	projectLink: "",
// 	githubLink: "",
// 	duration: "",
// 	technology: "",
// 	description: "",
// 	teamSize: "",
// 	myContribution: ""
// }
];

export default ProjectsData;
